version: '3'
services:
  mongo:
    image: mongo:3.2
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/messageApp
      - REDIS_URL=redis
  kv:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"
  # Kafka message broker
#   zookeeper:
#     image: wurstmeister/zookeeper
#     ports:
#       - "2181:2181"
#   kafka:
#     image: wurstmeister/kafka
#     ports:
#       - "9092:9092"
#     links:
#       - zookeeper:zk
#     environment:
#       KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
#       KAFKA_CREATE_TOPICS: "DATA:1:1"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
  # logentries:
  #   command: '-t 82855f8b-5341-34d5-3e54-12b612c26efa --no-stats'
  #   image: logentries/docker-logentries
  #   restart: always
  #   volumes:
  #     - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  mongo-data:
  redis-data:
  
